apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-store
  description: Pet store
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://github.com/LuisLiraC/openapi-spec-demo/blob/main/spec-demo.yml